# Generated by Django 3.2.25 on 2026-01-14 18:11

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
